config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#home'
  
  resources :orders do
    post 'billing', on: :member
    # post 'raffle', on: :collection
  end


  get 'customers/:token/opened', to: 'customers#opened'
  resources :customers
  resources :services
  resources :orders

  get 'refresh', to: :refresh, controller: 'orders'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :order

  validates :email, uniqueness: true, on: :create
  validates :email, presence: true
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :order
  
  enum recurrence: { "monthly" => 0, "quarterly" => 1, "semester" => 2, "yearly" => 3, "onetime" => 4, "two_or_more_times" => 5 } 

  validates :name, :price, :recurrence, presence: true

  def role_recurrence
    if self.recurrence == 'monthly'
      'Mensal'
    elsif self.recurrence == 'quarterly'
      'Trimestral'    
    elsif self.recurrence == 'semester'
      'Semestral'
    elsif self.recurrence == 'yearly'
      'Anual'
    elsif self.recurrence == 'onetime'
      'A vista'
    else
      'Parcelado'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_customer, only: [:edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(params_customer)
    if @customer.save
      redirect_to customers_path, notice: "O cliente (#{@customer.email}) foi cadastrado com sucesso"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @customer.update(params_customer)
      redirect_to customers_path, notice: "O cliente (#{@customer.email}) foi atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    customer_email = @customer.email

    if @customer.destroy
      redirect_to customers_path, notice: "O cliente (#{customer_email}) foi deletado com sucesso"
    else
      render :index
    end
  end

  private 

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def params_customer
      params.require(:customer).permit(:fullname, :email, :phone, :cpfcnpj, :address)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_orders, only: [:edit, :update, :destroy]
  before_action :set_moip_config, only: [:index, :create, :new, :edit, :update, :refresh]

  def index
    @orders = Order.all
  end

  def refresh
    @orders = Order.all

    api = Moip2::Api.new(set_moip_config)
    @orders.each do |f|
      # CONSULTA O STATUS DO PEDIDO E SALVA
      pagamento = api.order.show("#{f.moipid}")
      if f.status != pagamento[:status]
        @order = Order.find(f.id)
        @order.status = pagamento[:status]
        @order.save
      end
    end 
    render :index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params_order)
    @order.status = 'WAITING'

    if @order.save
      
      api = Moip2::Api.new(set_moip_config)
      order_moip = api.order.create({
        own_id: "#{@order.id}",
        items: [
          {
            product: "#{@order.service.name}",
            quantity: 1,
            detail: "#{@order.service.detail}",
            price: @order.service.price
          }
        ],
        customer: {
          own_id: "#{@order.customer.id}",
          fullname: "#{@order.customer.fullname}",
          email: "#{@order.customer.email}",
        }
      })

      # SALVA O ID DO PEDIDO DO MOIP NO REGISTRO DO BANCO
      @order.moipid = order_moip.id
      @order.instruction1 = "teste1"
      @order.instruction2 = "teste2"
      @order.instruction3 = "teste3"

      @order.link_boleto = order_moip._links[:checkout][:pay_boleto][:redirect_href]

      @order.save

      api.payment.create(order_moip.id,
      {
        # ...
          funding_instrument: {
              method: "BOLETO",
              boleto: {
                  expiration_date: "#{@order.expiration_date}",
                  instruction_lines: {
                      first: "#{@order.instruction1}",
                      second: "#{@order.instruction2}",
                      third: "#{@order.instruction3}"
                    },
                  logo_uri: "http://www.agenciadavos.com.br/themes/agenciadavos/images/logo_original.png"
              }
          }
      }
      )

      redirect_to orders_path, notice: "O Pedido (#{@order.id}) foi cadastrado com sucesso"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update(params_order)
      redirect_to orders_path, notice: "O Pedido (#{@order.id}) foi atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    order_id = @order.id

    if @order.destroy
      redirect_to orders_path, notice: "O Pedido (#{order_id}) foi deletado com sucesso"
    else
      render :index
    end
  end

  private 

  def set_orders
    @order = Order.find(params[:id])
  end

  def params_order
      params.require(:order).permit(:customer_id, :service_id, :expiration_date, :instruction1, :instruction2, :instruction3, :moipid, :status, :created_at)
  end

  def set_moip_config
    auth = Moip2::Auth::Basic.new("YXZ56UUSD2NUQFK0JOUJYNXMBFKYUS0E", "TM3KO0HINUCPKATVR4TCVB35KRGBIOUHGKEOL6AA")
    clientMoip = Moip2::Client.new(:sandbox, auth)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_services, only: [:edit, :update, :destroy]

  def index
    @services = Service.all
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(params_service)
    if @service.save
      redirect_to services_path, notice: "O serviço (#{@service.name}) foi cadastrado com sucesso"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @service.update(params_service)
      redirect_to services_path, notice: "O serviço (#{@service.name}) foi atualizado com sucesso"
    else
      render :edit
    end
  end

  def destroy
    service_name = @service.name

    if @service.destroy
      redirect_to services_path, notice: "O serviço (#{service_name}) foi deletado com sucesso"
    else
      render :index
    end
  end

  private 

  def set_services
    @service = Service.find(params[:id])
  end

  def params_service
      params.require(:service).permit(:name, :detail, :price, :recurrence)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custumers_helper.rb
module CustumersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
  OptionsForRecurrence = Struct.new(:id, :description)

  def options_for_recurrence
    # map mapeia e poupa de ter que mostrar valor da variavel
    Service.recurrences.map do |key, value|
      if value == 0
        value = 'Mensal'
      elsif value  == 1
        value = 'Trimestral'    
      elsif value  == 2
        value = 'Semestral'
      elsif value  == 3
        value = 'Anual'
      elsif value  == 4
        value = 'A vista'
      else
        value = 'Parcelado'
      end
      OptionsForRecurrence.new(key, value)
    end
  end
end

app/views/customers/edit.html.erb
<%= render partial: 'customers/shared/form', locals: {btn_title: "EDITAR"} %>

app/views/customers/index.html.erb
<div class="row campaigns">
  <h3>Clientes</h3>
  <br>

  <table class="responsive-table">
    <thead>
      <tr>
          <th>Nome / Razao Social</th>
          <th>Email</th>
          <th>Telefone</th>
          <th></th>
          <th></th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |c| %>
      <tr>
        <td><%= truncate(c.fullname, length: 30, omission: '...') %></td>
        <td><%= c.email %></td>
        <td><%= c.phone %></td>
        <td>
          <%= link_to edit_customer_path(c.id), class:"waves-effect waves-light btn cyan" do %>
            <i class="large material-icons">update</i>
          <% end %>
        </td>
        <td>
        <%= link_to customer_path(c.id), method: :delete, class:"waves-effect waves-light btn red" do %>
            <i class="large material-icons">delete</i>
        <% end %>  
      </tr>

      <% end %>
    </tbody>
  </table>
            



  <div class="fixed-action-btn campaigns-btn">
   <%= link_to new_customer_path, class:"btn-floating btn-large red pulse" do %>
    <i class="large material-icons">add</i>
   <% end %>
  </div>
</div>

app/views/customers/new.html.erb
<%= render partial: 'customers/shared/form', locals: {btn_title: "CADASTRAR"} %>

app/views/customers/shared/_form.html.erb
<% if @customer.errors.any? %> 
  <% @customer.errors.full_messages.each do |message| %>
    <script>Materialize.toast('<%= message %>', 4000, 'red')</script>
  <% end %>
<% end %>

<div class="row">
    <%= form_for(@customer, html: { class: "col s12" }) do |f| %>
       <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :fullname, class: "validate", placeholder: "Nome/Razao Social" %>
          <label for="first_name">Nome/Razao Social:</label>
        </div>
      </div>    
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :email, class: "validate", placeholder: "E-mail" %>
          <label for="first_name">Email:</label>
        </div>
      </div>    
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :cpfcnpj, class: "validate", placeholder: "CPF/CNPJ" %>        
          <label for="first_name">CPF/CNPJ</label>
        </div>
        <div class="input-field col s6">
          <%= f.text_field :phone, class: "validate", placeholder: "Telefone" %>
          <label for="last_name">Telefone</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :address, class: "validate", placeholder: "Endereço" %>
          <label for="email">Endereço</label>
        </div>
      </div>


      <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
        <i class="material-icons right">send</i> <%= btn_title %>
      <% end %>

      <%= link_to customers_path, class:"btn waves-effect waves-light red" do %>
         VOLTAR<i class="large material-icons">arrow_back</i>
      <% end %>

    <% end %>
  </div>

app/views/home/home.html.erb
<div class="row home">
  <div class="center">
    <h4 class="title">Sistema de gestão de boletos com o MOIP </h4>
    <h5 class="subtitle">Crie boletos de cobrança para seus clientes</h5>
    <h5 class="subtitle2">Rápido, fácil e garantido</h5>

    <%= form_tag("/orders", method: "post") do %>
      <%= submit_tag("Entrar agora", class: "waves-effect cyan btn home-button") %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NossoAmigoSecreto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>

    <header>
      <%= render "shared/navbar" %>
    </header>
    
    <br><br>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <%= render "shared/footer" %>
    </footer>

    <% if notice %>
        <script>
            Materialize.toast('<%= notice %>', 4000, 'green')
        </script>
    <% end %>

    <% if alert %>
        <script>
            Materialize.toast('<%= alert %>', 4000, 'red')
        </script>
    <% end %>
    

  </body>
</html>

app/views/orders/create.html.erb
<div class="row">
    <form class="col s12">
      <div class="row">
        <div class="input-field col s6">
          <input placeholder="Placeholder" id="first_name" type="text" class="validate">
          <label for="first_name">First Name</label>
        </div>
        <div class="input-field col s6">
          <input id="last_name" type="text" class="validate">
          <label for="last_name">Last Name</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input disabled value="I am not editable" id="disabled" type="text" class="validate">
          <label for="disabled">Disabled</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" class="validate">
          <label for="email">Email</label>
        </div>
      </div>
      <div class="row">
        <div class="col s12">
          This is an inline input field:
          <div class="input-field inline">
            <input id="email" type="email" class="validate">
            <label for="email" data-error="wrong" data-success="right">Email</label>
          </div>
        </div>
      </div>
    </form>
  </div>

app/views/orders/edit.html.erb
<%= render partial: 'orders/shared/form', locals: {btn_title: "ALTERAR"}  %>

app/views/orders/index.html.erb
<div class="row campaigns">
  <h3>Pedidos</h3>
  <br>
 
  <table class="responsive-table">
    <thead>
      <tr>
          <th>Moip ID</th>
          <th>Cliente</th>
          <th>Serviço</th>
          <th>Data de vencimento</th>
          <th>Valor</th>
          <th>Status</th>
          <th></th>
          <th></th>
          <th></th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |c| %>
      <tr>
        <td><%= c.moipid %></td>
        <td><%= c.customer.fullname %></td>
        <td><%= c.service.name %></td>
        <td><%= c.expiration_date  %></td>
        <td><%= c.service.price %></td>
        <%
          if c.status == 'WAITING'
            color = 'yellow lighten-1'
          elsif c.status == 'PAID'
            color = 'green darken-2'
          else 
            color = 'red darken-2'
          end
        %>
        <td>
          <span class="badge <%= color %>">
            <%= c.status %>
          </span>
        </td>
        <td>
          <a href="<%= c.link_boleto %>" target="_blank" class="waves-effect waves-light btn cyan">
            <i class="large material-icons">payment</i>
          </a>
        </td>        
        <td>
          <%= link_to edit_order_path(c.id), class:"waves-effect waves-light btn cyan" do %>
            <i class="large material-icons">update</i>
          <% end %>
        </td>
        <td>
        <%= link_to order_path(c.id), method: :delete, class:"waves-effect waves-light btn red" do %>
            <i class="large material-icons">delete</i>
        <% end %>  
      </tr>

      <% end %>
    </tbody>
  </table>
            



  <div class="fixed-action-btn campaigns-btn">
   <%= link_to new_order_path, class:"btn-floating btn-large red pulse" do %>
    <i class="large material-icons">add</i>
   <% end %>
  </div>


   <%= link_to refresh_path, class:"btn-floating btn-large waves-effect waves-light red" do %>
    <i class="large material-icons">refresh</i>
   <% end %>

</div>

app/views/orders/new.html.erb
<%= render partial: 'orders/shared/form', locals: {btn_title: "CADASTRAR"}  %>

app/views/orders/shared/_form.html.erb
  <% if @order.errors.any? %> 
  <% @order.errors.full_messages.each do |message| %>
    <script>Materialize.toast('<%= message %>', 4000, 'red')</script>
  <% end %>
<% end %>

<div class="row">
    <%= form_for(@order, html: { class: "col s12" }) do |f| %>
       <div class="row">
        <div class="col s12">
          <%= f.collection_select(:service_id, Service.all, :id, :name, class: "input-field" ) %>
          <label for="first_name">Serviço:</label>
        </div>
      </div>    
       <div class="row">
        <div class="col s12">
          <%= f.collection_select(:customer_id, Customer.all, :id, :fullname, class: "input-field" ) %>
          <label for="first_name">Cliente:</label>
        </div>
      </div>    
      <div class="row">
        <div class="input-field col s12">
          <%= f.date_field :expiration_date, class: 'datepicker' %>
          <label for="first_name">Data de vencimento:</label>
        </div>
      </div>    


      <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
        <i class="material-icons right">send</i> <%= btn_title %>
      <% end %>

      <%= link_to orders_path, class:"btn waves-effect waves-light red" do %>
         VOLTAR<i class="large material-icons">arrow_back</i>
      <% end %>

    <% end %>
  </div>

<script>
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15, // Creates a dropdown of 15 years to control year,
    today: 'Today',
    clear: 'Clear',
    close: 'Ok',
    closeOnSelect: false // Close upon selecting a date,
  });
</script>

app/views/services/edit.html.erb
<%= render partial: 'services/shared/form', locals: {btn_title: "ALTERAR"}  %>

app/views/services/index.html.erb
<div class="row campaigns">
  <h3>Serviços</h3>
  <br>
 
  <table class="responsive-table">
    <thead>
      <tr>
          <th>Nome</th>
          <th>Detalhes</th>
          <th>Preço</th>
          <th>Recorrencia</th>
      </tr>
    </thead>

    <tbody>
      <% @services.each do |c| %>
      <tr>
        <td><%= truncate(c.name, length: 30, omission: '...') %></td>
        <td><%= truncate(c.detail, length: 90, omission: '...')  %></td>
        <td><%= c.price %></td>
        <td><%= c.role_recurrence %></td>
        <td>
          <%= link_to edit_service_path(c.id), class:"waves-effect waves-light btn cyan" do %>
            <i class="large material-icons">update</i>
          <% end %>
        </td>
        <td>
        <%= link_to service_path(c.id), method: :delete, class:"waves-effect waves-light btn red" do %>
            <i class="large material-icons">delete</i>
        <% end %>  
      </tr>

      <% end %>
    </tbody>
  </table>
            



  <div class="fixed-action-btn campaigns-btn">
   <%= link_to new_service_path, class:"btn-floating btn-large red pulse" do %>
    <i class="large material-icons">add</i>
   <% end %>
  </div>
</div>

app/views/services/new.html.erb
<%= render partial: 'services/shared/form', locals: {btn_title: "CADASTRAR"}  %>

app/views/services/shared/_form.html.erb
 <% if @service.errors.any? %> 
  <% @service.errors.full_messages.each do |message| %>
    <script>Materialize.toast('<%= message %>', 4000, 'red')</script>
  <% end %>
<% end %>

<div class="row">
    <%= form_for(@service, html: { class: "col s12" }) do |f| %>
       <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :name, class: "validate", placeholder: "Nome" %>
          <label for="first_name">Nome:</label>
        </div>
      </div>    
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :detail, class: "validate", placeholder: "Detalhes" %>
          <label for="first_name">Detalhes:</label>
        </div>
      </div>    
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :price, class: "validate", placeholder: "Preço" %>        
          <label for="first_name">Preço:</label>
        </div>

        <div class="col s6">
          <label for="last_name">Recorrencia:</label>
          <%= f.collection_select :recurrence, options_for_recurrence, :id, :description, { prompt: "Escolha a recorrencia" }, class: "input-field" %>  
        </div>
      </div>



      <%= button_tag(type: "submit", class: "btn waves-effect waves-light") do %>
        <i class="material-icons right">send</i> <%= btn_title %>
      <% end %>

      <%= link_to services_path, class:"btn waves-effect waves-light red" do %>
         VOLTAR<i class="large material-icons">arrow_back</i>
      <% end %>

    <% end %>
  </div>

app/views/shared/_footer.html.erb
<div class="page-footer">
  <div class="container">
    <div class="copyright">
      <b>Criado por Vitor Águila </b>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav lighten-2">
    <div class="nav-wrapper col s12">
      <a href="/" class="brand-logo">
        <img src="/assets/logo.png" alt="" class="logo-img">
        <span class="logo-title">
          Gestão de clientes com o MOIP
        </span>
      </a>

      <a href="#" data-activates="side-bar" class="button-collapse"><i class="material-icons">menu</i></a>

      <ul class="right hide-on-med-and-down">
        <% if current_user %>
          <li><a href="/orders">Pedidos</a></li>
          <li><a href="/customers">Clientes</a></li>
          <li><a href="/services">Serviços</a></li>
          <li><a href="/users/edit">Perfil</a></li>
          <li>  <%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><a href="/users/sign_in">Entrar</a></li>
          <li><a href="/users/sign_up">Criar Conta</a></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>


<ul class="side-nav" id="side-bar">
  <% if current_user %>
    <li><a href="/orders">Pedidos</a></li>
    <li><a href="/customers">Clientes</a></li>
    <li><a href="/services">Serviços</a></li>
    <li><a href="/users/edit">Perfil</a></li>
    <li><div class="divider"></div></li>
    <li>  <%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
  <% else %>
    <li><a href="/users/sign_in">Entrar</a></li>
    <li><div class="divider"></div></li>
    <li><a href="/users/sign_up">Criar Conta</a></li>
    <li><div class="divider"></div></li>
  <% end %>
</ul>